### ISSUE TITLE
Undeclared variable target in Netcat class

### ISSUE THREAD

**Issue by kingofsystem** [rhelmot/nclib#10]
When i have created a TCPServer and started listening, when i trying to connect to my server it gave me an error. I have changed line 179 of netcat.py  `self.peer = target` to `self.peer = connect` and all works fine.

**Comment by rhelmot** [comment]
God, I'm sorry about that. I actually already had that fixed locally, but hadn't committed or pushed it yet. Thank you for letting me know!
