### ISSUE TITLE
An example send - receive

### ISSUE THREAD

**Issue by broccoli-2019** [rhelmot/nclib#15]
I would like to learn how to use nclib to make a Python3 program running on machine A to interact with another running on machine B through sending UDP packages to each other. As I am new to this, I am finding it difficult to follow the documentation.

Would you be so kind to show me a simple example of send <–> receive programs? Something very simple just to enable be to understand how it works. For instance, program A sends number x to program B. Program B do y = x + 2 and returns y to program A.  UDP please. Thank you

**Comment by rhelmot** [comment]
Socket interfaces these days provide the basic abstraction of sending streams (or blocks) of bytes from one computer to another. How you communicate meaningful data of other types over this channel is the process of "serialization".

There is a lot to learn about networking. nclib is a wrapper over the [python `socket` module](https://docs.python.org/3/library/socket.html), which is itself a wrapper over the [C socket APIs](https://linux.die.net/man/2/socket). nclib tries to simplify the interface into its most common cases while adding extra "sugar" features.

Here is an example program that does what you want, serializing the integer over a text-based protocol. If you wanted to use a binary protocol, you would serialize the data using the [struct module](https://docs.python.org/3/library/struct.html). You might be tempted to use pickle for serialization, but it is a very bad idea to pass pickled data over the network. Very bad things can happen.

program A (acting as the server, waits for program B to connect):

```python
import nclib
import sys

if len(sys.argv) < 2:
    print('usage: python a.py [integer]')

# here's the input value
value = int(sys.argv[1])
print(value, '+ 2 = ...')

# create a listening socket, bound to "any address"
# if your computer has multiple network interfaces you can specify one
# of those addresses to only listen for connections on that interface.
# This is listening on TCP port 1234.
nc = nclib.Netcat(listen=('0.0.0.0', 1234))

# serialize the value and send it over the wire
nc.send(str(value).encode())

# receive a response and deserialize it
value2 = int(nc.recv().decode())
print(value2)
```

Program B (connects to the server started by program A)

```python
import nclib

# connect to the server program running on this computer ("localhost")
# on TCP port 1234
nc = nclib.Netcat(connect=('localhost', 1234))

# receive and deserialize a value
value = int(nc.recv().decode())

# compute
value2 = value + 2

# serialize and send the result value
nc.send(str(value2).encode())
```
