### ISSUE TITLE
nclib broken on pypi

### ISSUE THREAD

**Issue by cognifloyd** [rhelmot/nclib#2]
I just tried upgrading nclib with `pip2 install nclib --upgrade --user`, but the nclib library wasn't installed. All I get is the serve-stdio bin and and a dist-info folder.

Downloading the [tar.gz](https://pypi.python.org/packages/bf/0c/32b46480bb9757585029e4228d641b610bbc7de5750f8d9d1f033e163efc/nclib-0.7.1.tar.gz#md5=52cc83137d07db0c2e6512180cd955ea) linked from https://pypi.python.org/pypi/nclib/0.7.1 shows that the tarball doesn't have any of the python code in it. The 0.7.0 tarball isn't any better.

Please fix your distribution.

**Comment by rhelmot** [comment]
sorry about that!!! I forgot that when changing a distribution from a single file (nclib.py) to a package (nclib containing netcat.py, server.py...) I had to tweak some settings. Fixed and uploaded!
