### ISSUE TITLE
How to simulate nc -z localhost 8080 with nclib

### ISSUE THREAD

**Issue by ichux** [rhelmot/nclib#21]
I just stumbled on this lovely Python library but do not have much knowledge of how things work with sockets.

Within my code, you will usually see me do `while ! nc -z localhost 8080; do sleep 0.5; echo "localhost:8080"; done` in a bash file.

I would like to do this with nclib but it's the *-z* part that I need help with. Please, how do I do `nc -z localhost 8080` with nclib?

Thanks

**Comment by rhelmot** [comment]
the `-z` flag is for port scanning, which nclib doesn't have designated interfaces for. However, you can simulate its behavior as follows:

```python
try:
  nclib.Netcat('localhost', 8080).close()
except nclib.NetcatError:
  connected = False
else:
  connected = True
```

**Comment by ichux** [comment]
@rhelmot 

I really appreciate your help. You rock!
