### ISSUE TITLE
Just me or is all the documentation gone?

### ISSUE THREAD

**Issue by havedill** [rhelmot/nclib#22]
Every page is blank, even a PDF version I've found has lots of blank pages

![image](https://github.com/rhelmot/nclib/assets/34009509/1ffa50a8-319d-4f82-989c-c525cfd49db7)

**Comment by rhelmot** [comment]
Seems like readthedocs is using a version of python that is incompatible with some of the typing features I'm using. Let me see what I can do...

**Comment by rhelmot** [comment]
I was able to fix it. Thanks for reporting, and let me know if there are more issues!
