### ISSUE TITLE
SimpleDuplex example

### ISSUE THREAD

**Issue by Derf000** [rhelmot/nclib#24]
Hi,

will it be possible to have a simple example of simpleDuplex usage ?

I don't really understand the function of this 'socket'.

Thanks for help..

**Comment by rhelmot** [comment]
If you're just looking to connect the contents of two sockets to each other you probably want `nclib.ferry`. The duplex functionality is for splicing one socket's recv and another socket's send into a single object.

**Comment by Derf000** [comment]
thanks for bringing this up 👍
