### ISSUE TITLE
IPv6 support missing

### ISSUE THREAD

**Issue by chbndrhnns** [rhelmot/nclib#5]
I tried to set additional socket options to enable IPv6 for a socket but those options are not exposed via the library. Could you add this easily?

**Comment by rhelmot** [comment]
I made the latest release just for you :)

![image](https://user-images.githubusercontent.com/2498805/30721382-a1375af0-9ee0-11e7-948e-a5d481f0923a.png)

**Comment by chbndrhnns** [comment]
👌
